// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using present_server.Data;

#nullable disable

namespace presentserver.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230106123223_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("present_server.Data.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarImgUrl")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CarYear")
                        .HasMaxLength(100)
                        .HasColumnType("INTEGER");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            CarBrand = "Audi",
                            CarDescription = "Good car",
                            CarImgUrl = "https://www.topgear.com/sites/default/files/cars-car/image/2021/03/audiuk0002282120audi20a420saloon.jpg",
                            CarModel = "A4",
                            CarYear = 2012
                        },
                        new
                        {
                            CarId = 2,
                            CarBrand = "Audi",
                            CarDescription = "Good car",
                            CarImgUrl = "https://www.topgear.com/sites/default/files/cars-car/image/2021/03/audiuk0002282120audi20a420saloon.jpg",
                            CarModel = "A4",
                            CarYear = 2012
                        },
                        new
                        {
                            CarId = 3,
                            CarBrand = "Audi",
                            CarDescription = "Good car",
                            CarImgUrl = "https://www.topgear.com/sites/default/files/cars-car/image/2021/03/audiuk0002282120audi20a420saloon.jpg",
                            CarModel = "A4",
                            CarYear = 2012
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
