const API_BASE_URL_DEVELOPMENT = `https://localhost:7025`;
const API_BASE_URL_PRODUCTION = `https://presentserver20230110125806.azurewebsites.net`;

const ENDPOINTS = {
  GET_ALL_CARS: "api/cars",
  GET_CARS_LENGTH: "api/cars/count",
  GET_CAR_BY_ID: "api/car",
  POST_CAR: "api/post",
  UPDATE_CAR: "api/update",
  DELETE_CAR_BY_ID: "api/delete",
};

const development = {
  API_URL_GET_ALL_CARS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_CARS}`,
  API_URL_GET_CARS_LENGTH: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CARS_LENGTH}`,
  API_URL_GET_CAR_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CAR_BY_ID}`,
  API_URL_POST_CAR: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.POST_CAR}`,
  API_URL_UPDATE_CAR: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_CAR}`,
  API_URL_DELETE_CAR_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_CAR_BY_ID}`,
};
const production = {
  API_URL_GET_ALL_CARS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_CARS}`,
  API_URL_GET_CARS_LENGTH: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CARS_LENGTH}`,
  API_URL_GET_CAR_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CAR_BY_ID}`,
  API_URL_POST_CAR: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.POST_CAR}`,
  API_URL_UPDATE_CAR: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_CAR}`,
  API_URL_DELETE_CAR_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_CAR_BY_ID}`,
};

const ApiRoutes =
  process.env.NODE_ENV === "development" ? development : production;

export default ApiRoutes;
